// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/alifmufthi91/ecommerce-system/services/order/internal/model"

	repository "github.com/alifmufthi91/ecommerce-system/services/order/internal/order/repository"
)

// StockLockRepository is an autogenerated mock type for the StockLockRepository type
type StockLockRepository struct {
	mock.Mock
}

// CreateStockLock provides a mock function with given fields: ctx, stockLock
func (_m *StockLockRepository) CreateStockLock(ctx context.Context, stockLock *model.StockLock) error {
	ret := _m.Called(ctx, stockLock)

	if len(ret) == 0 {
		panic("no return value specified for CreateStockLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.StockLock) error); ok {
		r0 = rf(ctx, stockLock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStockLocksByOrderID provides a mock function with given fields: ctx, orderID
func (_m *StockLockRepository) GetStockLocksByOrderID(ctx context.Context, orderID string) ([]model.StockLock, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetStockLocksByOrderID")
	}

	var r0 []model.StockLock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.StockLock, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.StockLock); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StockLock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithLockForUpdate provides a mock function with no fields
func (_m *StockLockRepository) WithLockForUpdate() repository.StockLockRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithLockForUpdate")
	}

	var r0 repository.StockLockRepository
	if rf, ok := ret.Get(0).(func() repository.StockLockRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.StockLockRepository)
		}
	}

	return r0
}

// WithReturning provides a mock function with no fields
func (_m *StockLockRepository) WithReturning() repository.StockLockRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithReturning")
	}

	var r0 repository.StockLockRepository
	if rf, ok := ret.Get(0).(func() repository.StockLockRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.StockLockRepository)
		}
	}

	return r0
}

// WithTX provides a mock function with given fields: tx
func (_m *StockLockRepository) WithTX(tx *gorm.DB) repository.StockLockRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTX")
	}

	var r0 repository.StockLockRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.StockLockRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.StockLockRepository)
		}
	}

	return r0
}

// NewStockLockRepository creates a new instance of StockLockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockLockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockLockRepository {
	mock := &StockLockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
