// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/alifmufthi91/ecommerce-system/services/warehouse/internal/model"
	payload "github.com/alifmufthi91/ecommerce-system/services/warehouse/internal/warehouse/payload"
	mock "github.com/stretchr/testify/mock"
)

// WarehouseService is an autogenerated mock type for the WarehouseService type
type WarehouseService struct {
	mock.Mock
}

// GetWarehouses provides a mock function with given fields: ctx
func (_m *WarehouseService) GetWarehouses(ctx context.Context) ([]model.Warehouse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetWarehouses")
	}

	var r0 []model.Warehouse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Warehouse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Warehouse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Warehouse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWarehouse provides a mock function with given fields: ctx, req
func (_m *WarehouseService) UpdateWarehouse(ctx context.Context, req payload.UpdateWarehouseReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWarehouse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, payload.UpdateWarehouseReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWarehouseService creates a new instance of WarehouseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseService {
	mock := &WarehouseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
