// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/alifmufthi91/ecommerce-system/services/shop/internal/model"

	repository "github.com/alifmufthi91/ecommerce-system/services/shop/internal/shop/repository"
)

// ShopRepository is an autogenerated mock type for the ShopRepository type
type ShopRepository struct {
	mock.Mock
}

// CreateShop provides a mock function with given fields: ctx, shop
func (_m *ShopRepository) CreateShop(ctx context.Context, shop *model.Shop) error {
	ret := _m.Called(ctx, shop)

	if len(ret) == 0 {
		panic("no return value specified for CreateShop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Shop) error); ok {
		r0 = rf(ctx, shop)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetShops provides a mock function with given fields: ctx
func (_m *ShopRepository) GetShops(ctx context.Context) ([]model.Shop, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetShops")
	}

	var r0 []model.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Shop, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Shop); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Shop)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithReturning provides a mock function with no fields
func (_m *ShopRepository) WithReturning() repository.ShopRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithReturning")
	}

	var r0 repository.ShopRepository
	if rf, ok := ret.Get(0).(func() repository.ShopRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ShopRepository)
		}
	}

	return r0
}

// WithTX provides a mock function with given fields: tx
func (_m *ShopRepository) WithTX(tx *gorm.DB) repository.ShopRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTX")
	}

	var r0 repository.ShopRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.ShopRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ShopRepository)
		}
	}

	return r0
}

// NewShopRepository creates a new instance of ShopRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShopRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShopRepository {
	mock := &ShopRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
